// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5FGp7IupIThThnfyIw821GkhOT_w_sLQ',
    appId: '1:226662222521:web:75e3d74108246fb3642968',
    messagingSenderId: '226662222521',
    projectId: 'fluterr-app',
    authDomain: 'fluterr-app.firebaseapp.com',
    storageBucket: 'fluterr-app.firebasestorage.app',
    measurementId: 'G-5TRCV7P8XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcmMw7_XyuUjJyNp-dAeD5krWVDg1fR8',
    appId: '1:226662222521:android:8c3352f658f17360642968',
    messagingSenderId: '226662222521',
    projectId: 'fluterr-app',
    storageBucket: 'fluterr-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcSHvZIftn3qm3aRiZJR35vETUJ-RpxI',
    appId: '1:226662222521:ios:e6da020ae29b26d5642968',
    messagingSenderId: '226662222521',
    projectId: 'fluterr-app',
    storageBucket: 'fluterr-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcSHvZIftn3qm3aRiZJR35vETUJ-RpxI',
    appId: '1:226662222521:ios:e6da020ae29b26d5642968',
    messagingSenderId: '226662222521',
    projectId: 'fluterr-app',
    storageBucket: 'fluterr-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5FGp7IupIThThnfyIw821GkhOT_w_sLQ',
    appId: '1:226662222521:web:c051ddb70881575d642968',
    messagingSenderId: '226662222521',
    projectId: 'fluterr-app',
    authDomain: 'fluterr-app.firebaseapp.com',
    storageBucket: 'fluterr-app.firebasestorage.app',
    measurementId: 'G-N89QTYR42S',
  );

}