name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/promociones/icono.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/promociones/banertt.jpg
    - assets/images/promociones/promo1.jpg
    - assets/images/promociones/promo2.jpg
    - assets/images/promociones/promo3.jpg
    - assets/images/promociones/icono.png  # 👈 icono que también usarás en splash

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/promociones/icono.png  # 👈 misma imagen que el icono
  android: true
  ios: true
  fullscreen: true
